//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.2
//     from Assets/InputSystem/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Character"",
            ""id"": ""131b0bb3-60b7-4b40-8852-b5999cbce9d6"",
            ""actions"": [
                {
                    ""name"": ""Movements"",
                    ""type"": ""Value"",
                    ""id"": ""155c9a1e-cd2c-4990-9f32-d2848ce209cd"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Tir"",
                    ""type"": ""Button"",
                    ""id"": ""855400ff-3eb1-4a6f-bdf8-30dcb59db666"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Enter"",
                    ""type"": ""Button"",
                    ""id"": ""63b2acc3-36d4-402f-a4ce-3b7067cff890"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""8e4cb25b-1ac9-4440-92d7-b7fe4f857d95"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Module1"",
                    ""type"": ""Button"",
                    ""id"": ""2f385c1e-4299-457f-957d-f7116cbe4c32"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Module2"",
                    ""type"": ""Button"",
                    ""id"": ""122a1fd4-f53f-4507-a00b-3b0f99408dbd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""8b00caf6-28bc-4185-8b5c-20fedf101397"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Kick"",
                    ""type"": ""Button"",
                    ""id"": ""d47d93a1-abae-4731-ad0e-cf365565df29"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchWeapon"",
                    ""type"": ""Value"",
                    ""id"": ""611e1b48-6057-4250-8650-6ae49983017c"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""9d0e1599-9f11-4b2e-9b9a-6ced39ac6f48"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movements"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""22680f2d-a6f3-47d1-86e2-f7c568c7da38"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Character"",
                    ""action"": ""Movements"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""20c3eb80-36cb-463f-8886-d540aad14e85"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Character"",
                    ""action"": ""Movements"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""09a74402-a666-44e1-ad7d-a217e03d4ec4"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Character"",
                    ""action"": ""Movements"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""dfe39a5d-0e03-46ec-80d2-7ead39042a37"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Character"",
                    ""action"": ""Movements"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0c9c3c2d-73f6-4fa6-bdbe-764af8dff296"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Character"",
                    ""action"": ""Tir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""caf1eea5-6894-4c0f-ae45-f1841c37147c"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Character"",
                    ""action"": ""Enter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1e9a425-7ebe-4f46-ba8b-bd88574d89da"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Character"",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""33f35110-6f26-43e6-8bab-ba125da92ca9"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Character"",
                    ""action"": ""Module1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""558ee6c1-99c6-42df-9ed0-69eff131ca36"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Character"",
                    ""action"": ""Module2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c38b6714-19a6-448b-bebe-0cf216a63755"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Character"",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80e041c8-55a0-4460-adb7-c4ab6c2e7b72"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Character"",
                    ""action"": ""Kick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ec8a8a7b-ab86-4cd6-9786-25392c1e4b3a"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Character"",
                    ""action"": ""SwitchWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Character"",
            ""bindingGroup"": ""Character"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<VirtualMouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Character
        m_Character = asset.FindActionMap("Character", throwIfNotFound: true);
        m_Character_Movements = m_Character.FindAction("Movements", throwIfNotFound: true);
        m_Character_Tir = m_Character.FindAction("Tir", throwIfNotFound: true);
        m_Character_Enter = m_Character.FindAction("Enter", throwIfNotFound: true);
        m_Character_MousePosition = m_Character.FindAction("MousePosition", throwIfNotFound: true);
        m_Character_Module1 = m_Character.FindAction("Module1", throwIfNotFound: true);
        m_Character_Module2 = m_Character.FindAction("Module2", throwIfNotFound: true);
        m_Character_Dash = m_Character.FindAction("Dash", throwIfNotFound: true);
        m_Character_Kick = m_Character.FindAction("Kick", throwIfNotFound: true);
        m_Character_SwitchWeapon = m_Character.FindAction("SwitchWeapon", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Character
    private readonly InputActionMap m_Character;
    private ICharacterActions m_CharacterActionsCallbackInterface;
    private readonly InputAction m_Character_Movements;
    private readonly InputAction m_Character_Tir;
    private readonly InputAction m_Character_Enter;
    private readonly InputAction m_Character_MousePosition;
    private readonly InputAction m_Character_Module1;
    private readonly InputAction m_Character_Module2;
    private readonly InputAction m_Character_Dash;
    private readonly InputAction m_Character_Kick;
    private readonly InputAction m_Character_SwitchWeapon;
    public struct CharacterActions
    {
        private @Controls m_Wrapper;
        public CharacterActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movements => m_Wrapper.m_Character_Movements;
        public InputAction @Tir => m_Wrapper.m_Character_Tir;
        public InputAction @Enter => m_Wrapper.m_Character_Enter;
        public InputAction @MousePosition => m_Wrapper.m_Character_MousePosition;
        public InputAction @Module1 => m_Wrapper.m_Character_Module1;
        public InputAction @Module2 => m_Wrapper.m_Character_Module2;
        public InputAction @Dash => m_Wrapper.m_Character_Dash;
        public InputAction @Kick => m_Wrapper.m_Character_Kick;
        public InputAction @SwitchWeapon => m_Wrapper.m_Character_SwitchWeapon;
        public InputActionMap Get() { return m_Wrapper.m_Character; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CharacterActions set) { return set.Get(); }
        public void SetCallbacks(ICharacterActions instance)
        {
            if (m_Wrapper.m_CharacterActionsCallbackInterface != null)
            {
                @Movements.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnMovements;
                @Movements.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnMovements;
                @Movements.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnMovements;
                @Tir.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnTir;
                @Tir.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnTir;
                @Tir.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnTir;
                @Enter.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnEnter;
                @Enter.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnEnter;
                @Enter.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnEnter;
                @MousePosition.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnMousePosition;
                @MousePosition.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnMousePosition;
                @MousePosition.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnMousePosition;
                @Module1.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnModule1;
                @Module1.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnModule1;
                @Module1.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnModule1;
                @Module2.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnModule2;
                @Module2.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnModule2;
                @Module2.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnModule2;
                @Dash.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnDash;
                @Kick.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnKick;
                @Kick.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnKick;
                @Kick.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnKick;
                @SwitchWeapon.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnSwitchWeapon;
                @SwitchWeapon.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnSwitchWeapon;
                @SwitchWeapon.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnSwitchWeapon;
            }
            m_Wrapper.m_CharacterActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movements.started += instance.OnMovements;
                @Movements.performed += instance.OnMovements;
                @Movements.canceled += instance.OnMovements;
                @Tir.started += instance.OnTir;
                @Tir.performed += instance.OnTir;
                @Tir.canceled += instance.OnTir;
                @Enter.started += instance.OnEnter;
                @Enter.performed += instance.OnEnter;
                @Enter.canceled += instance.OnEnter;
                @MousePosition.started += instance.OnMousePosition;
                @MousePosition.performed += instance.OnMousePosition;
                @MousePosition.canceled += instance.OnMousePosition;
                @Module1.started += instance.OnModule1;
                @Module1.performed += instance.OnModule1;
                @Module1.canceled += instance.OnModule1;
                @Module2.started += instance.OnModule2;
                @Module2.performed += instance.OnModule2;
                @Module2.canceled += instance.OnModule2;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @Kick.started += instance.OnKick;
                @Kick.performed += instance.OnKick;
                @Kick.canceled += instance.OnKick;
                @SwitchWeapon.started += instance.OnSwitchWeapon;
                @SwitchWeapon.performed += instance.OnSwitchWeapon;
                @SwitchWeapon.canceled += instance.OnSwitchWeapon;
            }
        }
    }
    public CharacterActions @Character => new CharacterActions(this);
    private int m_CharacterSchemeIndex = -1;
    public InputControlScheme CharacterScheme
    {
        get
        {
            if (m_CharacterSchemeIndex == -1) m_CharacterSchemeIndex = asset.FindControlSchemeIndex("Character");
            return asset.controlSchemes[m_CharacterSchemeIndex];
        }
    }
    public interface ICharacterActions
    {
        void OnMovements(InputAction.CallbackContext context);
        void OnTir(InputAction.CallbackContext context);
        void OnEnter(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
        void OnModule1(InputAction.CallbackContext context);
        void OnModule2(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnKick(InputAction.CallbackContext context);
        void OnSwitchWeapon(InputAction.CallbackContext context);
    }
}
